default: &default
  pool: 5
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: hash_development

test:
  <<: *default
  database: hash_test

# Heroku
production:
  <<: *default
  host: <%= ENV['DATABASE_URL'] %>
  database: app-dev
  username: user
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
