default: &default
  pool: 5
  host: localhost
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  username: user
  database: app-dev
#  database: hash_development

test:
  <<: *default
  database: hash_test

# Heroku
production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: app-dev
  username: user
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
