production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: app-dev
  username: user
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
