default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: hash_development

test:
  <<: *default
  database: hash_test


production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: app-dev
  username: user
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
